### ISSUE TITLE
V13 release

### ISSUE THREAD

**Issue by jharenza** [PediatricOpenTargets/OpenPBTA-analysis#395]
#### Which new datasets are being added with this release?
No new datasets

#### What is the sample breakdown (number of WGS, WXS, RNA-Seq, Panel, Methylation, other)?
Add PBTA samples: 
- [x] PBTA re-matched CBTN samples (335 T/N pairs) - [tab3](https://chop365-my.sharepoint.com/:x:/r/personal/zhangb1_chop_edu/_layouts/15/doc2.aspx?sourcedoc=%7B9B7B36C4-493D-4193-BA66-F3BDC85677B0%7D&file=CBTN%20X01%20Tumor-Normal%20pairing.xlsx&action=default&mobileredirect=true&cid=910bfdfb-14a1-49ff-a9cc-bcd6eb4a0193)
- [x] Project HOPE pair: BS_CKX0QTD6 and BS_S8756VS8 T/N WGS

Add NBL cell line (40) and PPTC PDX (244) RNA-Seq
<s>- [ ] https://github.com/d3b-center/bixu-tracker/issues/1910</s> (on hold)

Remove samples:
- [x] Remove `BS_XA1T7CAX` from methyl matrices.

MAF update:
- [x] Liftover hotspot file to GENCODE v39 gene symbols ([ticket](https://github.com/d3b-center/bixu-tracker/issues/1903))
- [x] Update BRAF canonical transcript to `ENST00000646891`
- [x] Review initial hotspot hg19 file to make sure we are creating the appropriate protein change hotspot TSV (@migbro)

Clinical:
- [x] Create sub-cohorts for internal use https://github.com/d3b-center/d3b-dbt-study-transforms/issues/72
- [x] Update mioncoseq clinical and break mioncoseq out as its own cohort https://github.com/d3b-center/d3b-dbt-study-transforms/issues/74
- [x] Update to EFS_days and EFS_event_type for PBTA as [here](https://github.com/d3b-center/d3b-dbt-study-transforms/pull/66) d3b-center/ticket-tracker-OPC#540 
- [x] Harmonize race and ethnicity fields https://github.com/d3b-center/d3b-dbt-study-transforms/issues/73
- [x] Harmonize mioncoseq normal composition https://github.com/d3b-center/d3b-dbt-study-transforms/issues/75
- [x] Update mioncoseq pathology dx (Jenn)
<s>- [ ] Add PPTC histologies file to dbt repo </s>(on hold)
<s>- [ ] Add Maris NBL cell line file to dbt repo </s>(on hold)

Splicing:
- [x] Release rMATs merged file <s>- needs re-merge with NBL cell line + PDX </s>

#### What data file(s) are added/updated/removed in this release?

[**Pre-release files**]
- [x] histologies-base.tsv
- [x] cnv-cnvkit.seg.gz
- [ ] cnvkit_with_status.tsv
- [x] cnv-controlfreec.tsv.gz
- [ ] cnv-consensus-gistic.zip
- [ ] cnv-consensus.seg.gz
- [ ] cnv-gatk.seg.gz
- [ ] consensus_seg_with_status.tsv 
- [ ] consensus_wgs_plus_cnvkit_wxs.tsv.gz
- [ ] consensus_wgs_plus_cnvkit_wxs_x_and_y.tsv.gz
- [ ] consensus_wgs_plus_cnvkit_wxs_autosomes.tsv.gz
- [x] fusion-arriba.tsv.gz
- [x] fusion-dgd.tsv.gz
- [x] fusion-putative-oncogenic.tsv
- [x] fusion-starfusion.tsv.gz
- [ ] fusion_summary_embryonal_foi.tsv
- [ ] fusion_summary_ependymoma_foi.tsv
- [ ] fusion_summary_ewings_foi.tsv
- [ ] fusion_summary_lgat_foi.tsv
- [x] snv-consensus-plus-hotspots.maf.tsv.gz
- [x] sv-manta.tsv.gz
- [ ] snv-mutation-tmb-all.tsv
- [ ] snv-mutation-tmb-coding.tsv
- [x] gene-expression-rsem-tpm-collapsed.rds
- [x] gene-counts-rsem-expected_count-collapsed.rds
- [x] tcga-gene-expression-rsem-tpm-collapsed.rds
- [x] tcga-gene-counts-rsem-expected_count-collapsed.rds
- [x] rna-isoform-expression-rsem-tpm.rds
- [x] methyl-m-values.rds
- [x] methyl-cn-values.rds
- [x] methyl-beta-values.rds
- [ ] independent-specimens.rnaseq.primary-plus.pre-release.tsv
- [ ] independent-specimens.rnaseq.primary.pre-release.tsv
- [ ] independent-specimens.rnaseq.relapse.pre-release.tsv

[**Commit files**]
- [ ] histologies.tsv
- [ ] efo-mondo-map.tsv
- [ ] ensg-hugo-pmtl-mapping.tsv
- [ ] uberon-map-gtex-group.tsv
- [ ] uberon-map-gtex-subgroup.tsv
- [ ] independent-specimens.methyl.primary-plus.eachcohort.tsv
- [ ] independent-specimens.methyl.primary-plus.tsv
- [ ] independent-specimens.methyl.primary.eachcohort.tsv
- [ ] independent-specimens.methyl.primary.tsv
- [ ] independent-specimens.methyl.relapse.eachcohort.tsv
- [ ] independent-specimens.methyl.relapse.tsv
- [ ] independent-specimens.rnaseqpanel.primary-plus.eachcohort.tsv
- [ ] independent-specimens.rnaseqpanel.primary-plus.tsv
- [ ] independent-specimens.rnaseqpanel.primary.eachcohort.tsv
- [ ] independent-specimens.rnaseqpanel.primary.tsv
- [ ] independent-specimens.rnaseqpanel.relapse.eachcohort.tsv
- [ ] independent-specimens.rnaseqpanel.relapse.tsv
- [ ] independent-specimens.wgs.primary-plus.eachcohort.tsv
- [ ] independent-specimens.wgs.primary-plus.tsv
- [ ] independent-specimens.wgs.primary.eachcohort.tsv
- [ ] independent-specimens.wgs.primary.tsv
- [ ] independent-specimens.wgs.relapse.eachcohort.tsv
- [ ] independent-specimens.wgs.relapse.tsv
- [ ] independent-specimens.wgswxspanel.primary-plus.eachcohort.prefer.wgs.tsv
- [ ] independent-specimens.wgswxspanel.primary-plus.eachcohort.prefer.wxs.tsv
- [ ] independent-specimens.wgswxspanel.primary-plus.prefer.wgs.tsv
- [ ] independent-specimens.wgswxspanel.primary-plus.prefer.wxs.tsv
- [ ] independent-specimens.wgswxspanel.primary.eachcohort.prefer.wgs.tsv
- [ ] independent-specimens.wgswxspanel.primary.eachcohort.prefer.wxs.tsv
- [ ] independent-specimens.wgswxspanel.primary.prefer.wgs.tsv
- [ ] independent-specimens.wgswxspanel.primary.prefer.wxs.tsv
- [ ] independent-specimens.wgswxspanel.relapse.eachcohort.prefer.wgs.tsv
- [ ] independent-specimens.wgswxspanel.relapse.eachcohort.prefer.wxs.tsv
- [ ] independent-specimens.wgswxspanel.relapse.prefer.wgs.tsv
- [ ] independent-specimens.wgswxspanel.relapse.prefer.wxs.tsv

[**Bed files and sample mapping**]
- [x] biospecimen_id_to_bed_map.txt
- [x] ashion_exome_v2_targets_hg38_padded100.bed
- [x] hg38_strelka.bed
- [x] intersect_cds_lancet_strelka_mutect_WGS.bed
- [x] intersect_strelka_mutect_WGS.bed
- [x] nexterarapidcapture_exome_targetedregions_v1.2_hg38_100.bed
- [x] S0274956_Padded_HG38.merged.bed
- [x] S02972011_Covered_hg38_100.bed
- [x] S04380110_Regions_hg38_100.bed
- [x] S07604715_100bp_Padded.bed
- [x] SeqCap_EZ_Exome_v2_Padded_HG38.merged.bed
- [x] StrexomeLite_hg38_liftover_100bp_padded.bed
- [x] Strexome_targets_intersect_sorted_padded100.GRCh38.bed
- [x] TARGET_AML_NBL_WT_SeqVal79_attempt06_AllTracks_HG38_bed_expanded100.bed
- [x] truseq-exome-targeted-regions-manifest-v1-2_hg38_100.bed
- [x] wgs_canonical_calling_regions.hg38.bed
- [x] WGS.hg38.lancet.300bp_padded.bed
- [x] WGS.hg38.lancet.unpadded.bed
- [x] WGS.hg38.mutect2.vardict.unpadded.bed
- [x] WGS.hg38.strelka2.unpadded.bed
- [x] WGS.hg38.vardict.100bp_padded.bed
- [x] xgen-exome-research-panel-targets_hg38_ucsc_liftover.100bp_padded.sort.merged.bed

[**File descriptions and notes**]
- [ ] data-files-description.md
- [ ] release-notes.md

**Comment by jharenza** [comment]
@zhangb1 can your team prepare the cnvkit, freec, and gatk cnv merge files above using [this](https://github.com/d3b-center/histologies-qc/blob/9d3b486abb8f0e016738371e647fedf3b16286ce/output/2023-06-02_histologies-base.tsv) histologies file please?

**Comment by zhangb1** [comment]
@jharenza  , yes, checking now

**Comment by jharenza** [comment]
> @jharenza  , yes, checking now

Can you also add manta to this? Thanks

**Comment by zhangb1** [comment]
yes, mantaSV will be in the merge

**Comment by zhangb1** [comment]
```
a8f8b36b68dc96421e1017b806fe12ca  cnv-cnvkit.seg.gz
4b34f5dd4fef1a717ec7e4975b906ebf  cnv-controlfreec.tsv.gz
33a2a02851ede7caeb23f974ee2ab9cc  cnv-gatk.seg.gz
25ea7fdf71413585008beb4e8aef6092  sv-manta.tsv.gz
```
Copy number and SV merged files are uploaded to the v13 folder s3://d3b-openaccess-us-east-1-prd-pbta/open-targets/v13/.  md5 also updated.

**Comment by zhangb1** [comment]
```
f49a13a9a8b57b969a6d8d7c247b3829  cnv-cnvkit.seg.gz
9cad15bade5e79b54d0e3e3a01d180a1  cnv-controlfreec.tsv.gz
ca066160895776d7f9daa2f7d42197ac  cnv-gatk.seg.gz
3ad8831f59efebdc93fe3acfdc1acf0a  snv-consensus-plus-hotspots.maf.tsv.gz
f9d6357ef2a033ca0e6d56235796252c  sv-manta.tsv.gz
```

these 5 files are updated in the DWH, please let me know anything issues  @jharenza

**Comment by zhangb1** [comment]
there are some Tumor samples with multiple normals in the CBTN extras, and we have to remove the duplicate, 

update the merge files in S3:

```
ac522fa2b5145314e471e8f3e1f068c2  cnv-cnvkit.seg.gz
c884e5e2a259ea2b4b6afa95b7bbf791  cnv-controlfreec.tsv.gz
a9c40f97de35f3f2844c5d8290800919  cnv-gatk.seg.gz
c62ba3491340886b048bfb5e68e8447b  snv-consensus-plus-hotspots.maf.tsv.gz
1b2b76bcd0db75f23a47cb3bab415d2d  sv-manta.tsv.gz
```

**Comment by jharenza** [comment]
> there are some Tumor samples with multiple normals in the CBTN extras, and we have to remove the duplicate,
> 
> update the merge files in S3:
> 
> ```
> ac522fa2b5145314e471e8f3e1f068c2  cnv-cnvkit.seg.gz
> c884e5e2a259ea2b4b6afa95b7bbf791  cnv-controlfreec.tsv.gz
> a9c40f97de35f3f2844c5d8290800919  cnv-gatk.seg.gz
> c62ba3491340886b048bfb5e68e8447b  snv-consensus-plus-hotspots.maf.tsv.gz
> 1b2b76bcd0db75f23a47cb3bab415d2d  sv-manta.tsv.gz
> ```

@zhangb1 @yuankunzhu do you have a cavatica project for the merge files? @zzgeng is going through QC but `cnv-gatk.seg.gz` seems to be empty

**Comment by jharenza** [comment]
I am going to start a new issue for this since so much has changed
